### ISSUE TITLE
GPL or MIT

### ISSUE THREAD

**Issue by DE0CH** [auto-optimization/iracepy#1]
I see that the package uses GPL as its license but it's a copyleft license. Is there a reason for this? Would it be better to use a more compatible and permissive license like MIT?

**Comment by MLopez-Ibanez** [comment]
I don't like companies taking my code and using it in closed source software without permission. If code is open-source, it should stay open-source.

**Comment by MLopez-Ibanez** [comment]
But I can be convinced that, in particular situations, using the MIT license may be better.

**Comment by DE0CH** [comment]
Sure I see what you mean. Put aside the whole capitalist argument about how money makes the world go around, having a more permissive license is almost useful in other situations. For example, we don't have `gcc` with `LLVM` as the backend because of the GPL incompatibility.

**Comment by MLopez-Ibanez** [comment]
When we meet in person, please remind me about this discussion because I was contributing to GCC at the time (search for my name in https://gcc.gnu.org/onlinedocs/gcc/Contributors.html) and can perhaps give you a more detailed picture of why we don't have gcc with llvm as a backend. 

In any case, if the license prevents you from contributing to this repository, I'm happy to change it.

**Comment by DE0CH** [comment]
I will remind you. Looking forward to that discussion! 

I don't think the license is a problem. I was just curious.
