### ISSUE TITLE
Create setup.py to build the package

### ISSUE THREAD

**Issue by MLopez-Ibanez** [auto-optimization/iracepy#10]
See: https://docs.python.org/3/distutils/setupscript.html

and examples here: https://github.com/anyoptimization/pymoo/blob/main/setup.py
and here: https://github.com/optuna/optuna/blob/master/setup.py

**Comment by DE0CH** [comment]
What do you mean by building the package? Is there anything to build? User can just install irace with R and install the pacakge with pip currently.

**Comment by MLopez-Ibanez** [comment]
The main purpose of the setup script is to describe your module distribution to the Distutils, so that the various commands that operate on your modules do the right thing.

From: https://docs.python.org/3/distutils/setupscript.html

**Comment by DE0CH** [comment]
Doesn't `pyproject.toml` does the same thing?

**Comment by MLopez-Ibanez** [comment]
Maybe, can it install the irace package so we can get rid of `install.py` ?
 
Also, shouldn't the dependencies be read from `python-requirements.txt`? It would be best to avoid having the same information in two difference places.

**Comment by DE0CH** [comment]
> Maybe, can it install the irace package so we can get rid of `install.py` ?

Yes. I will work on it and push to main.

> Also, shouldn't the dependencies be read from `python-requirements.txt`? It would be best to avoid having the same information in two difference places.

I don't think there's any way to read from `python-requirements.txt`. I think we can just get rid of `python-requirements.txt`.

**Comment by DE0CH** [comment]
Actually, I was wrong, [it can't](https://stackoverflow.com/questions/59802468/post-install-script-with-python-poetry). We can either just use setuptools or ask the user to install irace themselves with a command provided in readme. I would prefer to second way because it's more explicit and the user understands what happening. Afterall, installing a python package shouldn't try to install a r package.

**Comment by MLopez-Ibanez** [comment]
I would prefer to simplify the life of the user as much as possible, but we can also see how complicated is to setup continuous integration with Github Actions, where the package should be installed how a user would install it and then see if it is worth to simplify the installation.

**Comment by DE0CH** [comment]
A few comments after setting up the CI:

`requirements.txt` is needed because otherwise setup-python would complain. Also it seems that by convention this file includes the development dependencies like `pytest` and `codecov`. 

As for installing the irace R package in `setup.py`. I think since it just takes one line of command to install irace and we can't really help the user install R since there are so many different packaging formats, I think we should just leave it to the user.

**Comment by MLopez-Ibanez** [comment]
pymoo have the requirements for testing under `tests/`. See: https://github.com/anyoptimization/pymoo/blob/main/.github/workflows/testing.yml
They don't have requirements.txt in the root directory.

**Comment by DE0CH** [comment]
Oh yeah you're right. It just checks for `**/requirements.txt`.

**Comment by MLopez-Ibanez** [comment]
I think we unfortunately need a setup.py if we want to use the development mode of `pip` (I find installing the package while developing it too slow):

https://python-packaging-tutorial.readthedocs.io/en/latest/setup_py.html

**Comment by DE0CH** [comment]
We can have a minimal `setup.py` to enable editable install. You can just do `pip3 install -e .` and it will just use the library in place. 

Alternative, you can add the `src` path to the environment variable `PYTHONPATH` and it will just discover the irace package.

**Comment by MLopez-Ibanez** [comment]
It seems that with a recent setuptools, the setup.py file is not required for editable install. So I have removed it (it was actually not working at all for me anyway).
